#ifndef ZOMBIE_WALK_ANIM_H
#define ZOMBIE_WALK_ANIM_H

#define ZOMBIE_WALK_WIDTH  30
#define ZOMBIE_WALK_HEIGHT 47
#define ZOMBIE_WALK_FRAMES 7

extern unsigned char zombie_walk_frames[ZOMBIE_WALK_FRAMES][ZOMBIE_WALK_WIDTH*ZOMBIE_WALK_HEIGHT];

#endif
