#ifndef PLANT_TYPE_H
#define PLANT_TYPE_H

enum PlantType {
    PLANT_PEASHOOTER,
    PLANT_SNOW_PEASHOOTER,
    PLANT_SUNFLOWER,
    PLANT_JALAPENO,
    PLANT_POTATO_MINE,
    PLANT_WALLNUT,
    PLANT_CHOMPER,
    PLANT_GATLING_PEA
};

#endif
